name: CI
run-name: Testing quickie by @${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
    contents: read

env:
    NODE_ENV:           development
    NODE_OPTIONS:       "--experimental-vm-modules"
    NODE_NO_WARNINGS:   "1"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [24.x,25.x,26.x]

        steps:
              - name: Checkout code
                uses: actions/checkout@v6

              - name: Install package manager
                run: |
                    corepack enable
                    corepack install
                    yarn install --mode update-lockfile

              - name: Setup NodeJS ${{ matrix.node-version }}
                uses: actions/setup-node@v6
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "yarn"

              - name: Install dependencies
                run: yarn install --immutable

              - name: Check formatting
                run: yarn lint

              - name: Build packages
                run: yarn b:all
